### ISSUE TITLE
Dropout forward pass

### ISSUE THREAD

**Issue by camrongodbout** [lightaime/cs231n#1]
Hey, I've been using your code to compare against my own and you've done an amazing job helping out with going through the assignments with clean code.

In the dropout forward pass of assignment two I noticed you have 
`mask = (np.random.rand(*x.shape) >= p) / (1-p)`
And this makes so that your drop out matches your p. But according to the class notes: # probability of keeping a unit active. higher = less dropout

so I believe the line should read:
`mask = (np.random.rand(*x.shape) < p) / p`

I'm curious because I hope others continue to use your code to learn and get through the class as I have 👍

**Comment by lightaime** [comment]
Thank you for approving my job.
I think there some ambiguous statements in the standford's notes and assignments. 

In the neural-networks-2 note, 
> p: Probability of keeping a unit active.
However, in the assignment 2,
> p: Dropout parameter. We drop each neuron output with probability p. 

The two different stataments might confuse you. You could check it up.
