### ISSUE TITLE
An issue in Assignment2, fc_net.py

### ISSUE THREAD

**Issue by Jiangy3** [lightaime/cs231n#10]
In my opinion,
In line 266, the index of  ar_cache should be self.num_layers-1 instead of self.num_layers due to the for loop you used in line 255(self.num_layers-1 is excluded here)
Therefore, a minor change should be made in line 294 as well.
Since you use the index of the output layer (self.num_layers) consistently, your code works perfectly. However, for numerical continuity, there should be self.num_layers-1.
Your code helps me a lot, Thanks so much!
Happy Spring Festival!

**Comment by lightaime** [comment]
Thanks for your comments. This repo is just shared for the self taught students who are interested in solving the assignments of cs231n. Noice that there may be flaws in my solutions. But this repo will not be updated anymore.
