### ISSUE TITLE
issues as line127 k_nearest_neighbor.py  

### ISSUE THREAD

**Issue by Stevewsw** [lightaime/cs231n#5]
https://github.com/lightaime/cs231n/blob/ebeb3ef9c24d8be1f741fc24b3b63a3a543f3bb0/assignment1/cs231n/classifiers/k_nearest_neighbor.py#L127

the fundemental idea just like : (a - b)2 = a2 + b2 - 2ab

    A = np.sum(np.square(X), axis=1)   # 500 x 1

    B = np.transpose(np.sum(np.square(X_train), axis=1))  # 1x5000

    two_AB = 2*np.dot(X, self.X_train.T)   # 500 x 5000 

    dicts = np.sqrt(A + B - two_AB)`

how could it be broadcasted together with shapes (500,) (1,5000) ?
![image 334](https://user-images.githubusercontent.com/27012429/34611168-5fcef94c-f25f-11e7-999c-8b1986b5f6cb.png)

**Comment by chengziHome** [comment]
I also think the transpose should be applied to the second part(in other words, np.sum(np.square(self.X_train), axis = 1) )

**Comment by lightaime** [comment]
Thanks for your comments. There are two broadcast sums in this line.
The first one is: (500, 5000) + (500, )-> (500, 5000). //row broadcast
Then, the second one is:  (500, 5000) + (1, 5000) -> (500, 5000). //column broadcast
