### ISSUE TITLE
if it should be 'range' in python3.x

### ISSUE THREAD

**Issue by Stevewsw** [lightaime/cs231n#6]
https://github.com/lightaime/cs231n/blob/ebeb3ef9c24d8be1f741fc24b3b63a3a543f3bb0/assignment1/cs231n/classifiers/k_nearest_neighbor.py#L127

the fundemental idea just like : (a - b)2 = a2 + b2 - 2ab

`    A = np.sum(np.square(X), axis=1)   # 500 x 1
    B = np.transpose(np.sum(np.square(X_train), axis=1))  # 1x5000
    two_AB = 2*np.dot(X, self.X_train.T)   # 500 x 5000 
    dicts = np.sqrt(A + B - two_AB)`

how could it be broadcasted together with shapes (500,) (1,5000) ?

and anther one,  at line 143, 
for i in xrange(num_test):

range should be located here ?

**Comment by lightaime** [comment]
refer to #5
